'''
Created on 5 Apr 2017

@author: jdrumgoole
'''

import subprocess
import os
import sys

import requests

if __name__ == '__main__':
    print( '''
For this next set of examples we are going to use a public data set.
Lets download the zips.json file. A collection of ZIP codes for the US
in json format.

This data is hosted on github at :

https://github.com/jdrumgoole/back-to-basics-with-mongodb/tree/master/data
    ''')

    MONGOIMPORTCMD = "/usr/local/mongodb/bin/mongoimport"
        
    print( "Downloading restaurants")
    r = requests.get( "https://raw.githubusercontent.com/jdrumgoole/back-to-basics-with-mongodb/master/data/nyc_restaurants.json", stream=True)
    with open("nyc_restaurants.json", 'wb') as fd:
        for chunk in r.iter_content(chunk_size=128):
            fd.write(chunk)
    print( "Created nyc_restaurants.json")

    #
    # can't import line by line and convert to json because mongoexport recognises data preserving meta data. e.g. $date
    # operators that were generated by mongoexport
    #
    
    if not os.path.exists( MONGOIMPORTCMD ):
        print( "Can't find: '%s'" % MONGOIMPORTCMD )
        print( "Please edit %s and define MONGOIMPORTCMD correctly" % sys.argv[0] )
        print( "Current value is MONGOIMPORTCMD = '%s'" % MONGOIMPORTCMD )
        sys.exit( 2 )
        
    print( "Importing restaurants into mongodb")
    cmd= MONGOIMPORTCMD + " -d b2b -c restaurants --drop nyc_restaurants.json"
    subprocess.check_call( cmd, shell=True )

            
            
            